const projects = [
  {
    slug: "api-generator",
    title: "api-generator",
    description:
      "Generates a self-contained, typed TypeScript API client from an OpenAPI 3.0 spec over HTTP.",
    tagline:
      "Generate an opinionated, typed TypeScript API client from an OpenAPI 3.0 spec, served over HTTP.",
    repoUrl: "https://github.com/dapidicom/api-generator-ts",
    summary:
      "A Node.js service that turns your OpenAPI 3.0 spec into a self-contained, typed TypeScript API client you can import and call. You provide the spec; it returns the client.",
    sections: [
      {
        heading: "Usage",
        blocks: [
          { type: "h3", text: "1. Start the server" },
          {
            type: "code",
            language: "sh",
            code: "npm install\nnpm run build\nPORT=3000 npm start   # PORT defaults to 3000",
          },
          { type: "h3", text: "2. Generate a client from your spec" },
          {
            type: "p",
            text: "`POST /generate` takes your OpenAPI 3.0 JSON object and returns `{ \"typescript\": \"...\" }`. Save the `typescript` field to a file in your project:",
          },
          {
            type: "code",
            language: "sh",
            code: "curl -s http://localhost:3000/generate \\\n  -H 'Content-Type: application/json' \\\n  --data @openapi.json \\\n  | jq -r '.typescript' > src/api/client.ts",
          },
          { type: "p", text: "Given this spec (`openapi.json`):" },
          {
            type: "code",
            language: "json",
            code: `{
  "openapi": "3.0.0",
  "info": { "title": "Pet Store", "version": "1.0.0" },
  "paths": {
    "/pets/{petId}": {
      "get": {
        "operationId": "getPet",
        "parameters": [
          { "name": "petId", "in": "path", "required": true, "schema": { "type": "string" } }
        ],
        "responses": {
          "200": {
            "description": "ok",
            "content": {
              "application/json": { "schema": { "$ref": "#/components/schemas/Pet" } }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "Pet": {
        "type": "object",
        "required": ["id"],
        "properties": {
          "id": { "type": "integer" },
          "name": { "type": "string" }
        }
      }
    }
  }
}`,
          },
          { type: "p", text: "the generator emits:" },
          {
            type: "code",
            language: "ts",
            code: `// Auto-generated by api-generator-ts. Do not edit.
// Source: Pet Store 1.0.0

/* ===== Types ===== */
export interface Pet {
  id: number;
  name?: string;
}

/* ===== Client ===== */
export class ApiClient {
  constructor(private readonly baseUrl: string, private readonly fetchFn: typeof fetch = fetch) {}

  async getPet(petId: string): Promise<Pet> {
    const url = new URL(\`\${this.baseUrl}/pets/\${petId}\`);
    const res = await this.fetchFn(url.toString(), undefined);
    if (!res.ok) throw new Error(\`GET /pets/{petId} failed: \${res.status}\`);
    return (await res.json()) as Pet;
  }
}`,
          },
          { type: "h3", text: "3. Call it from your app" },
          {
            type: "code",
            language: "ts",
            code: `import { ApiClient } from './api/client';

const client = new ApiClient('https://api.example.com');

const pet = await client.getPet('42');
console.log(pet.name);`,
          },
          { type: "p", text: "The generated client:" },
          {
            type: "ul",
            items: [
              "is self-contained — no runtime dependency;",
              "uses the global `fetch`, available in Node.js 20+ and browsers;",
              "takes your API's base URL as its only constructor argument;",
              "uses `operationId` as the method name when present, otherwise derives one from the path and HTTP method;",
              "makes path parameters required arguments, query parameters an optional `params` object, and a JSON request body a required `body` argument;",
              "throws an `Error` on a non-2xx response.",
            ],
          },
        ],
      },
      {
        heading: "Run",
        blocks: [
          {
            type: "code",
            language: "sh",
            code: "npm install\nnpm run build\nPORT=3000 npm start   # PORT defaults to 3000",
          },
        ],
      },
      {
        heading: "Endpoints",
        blocks: [
          {
            type: "table",
            headers: ["Method", "Path", "Body", "Response"],
            rows: [
              ["GET", "/health", "—", '200 {"status":"ok"}'],
              ["POST", "/generate", "OpenAPI 3.0 JSON object", '200 {"typescript":"..."}'],
              ["POST", "/validate", "OpenAPI 3.0 JSON object", '200 {"valid":true,"errors":[]}'],
            ],
          },
          {
            type: "p",
            text: "`POST /generate` returns `400 {\"error\":\"...\"}` for invalid JSON or a spec without a `paths` object.",
          },
        ],
      },
      {
        heading: "Validation",
        blocks: [
          {
            type: "p",
            text: "`POST /validate` checks a spec's structural conformance against the official OpenAPI 3.0 JSON Schema (`spec.openapis.org/oas/3.0/schema/2024-10-18`), which is a draft-04 dialect validated with `ajv-draft-04`. A conforming spec returns `200 {\"valid\":true,\"errors\":[]}`; a non-conforming one returns `200 {\"valid\":false,\"errors\":[...]}` where each error carries a JSON-pointer `path`, a `message`, and the failing `keyword`. A non-JSON body returns `400 {\"error\":\"Request body is not valid JSON\"}`.",
          },
          {
            type: "p",
            text: "Validation is stricter than generation: the official schema requires `openapi`, `info`, and `paths`, and an `info` with `title` and `version`, whereas `/generate` only checks for a `paths` object.",
          },
          {
            type: "p",
            text: "`$ref` resolution and semantic checks (dangling refs, `operationId` collisions) are out of scope; `/validate` enforces the schema's structure only.",
          },
        ],
      },
      {
        heading: "Output",
        blocks: [
          {
            type: "p",
            text: "For each `components.schemas` entry the generator emits an interface (for object schemas) or a type alias. It then emits an `ApiClient` class with one async method per operation, using `operationId` when present. Path parameters become required arguments, query parameters an optional `params` object, and a JSON request body a required `body` argument. The `2xx` JSON response schema drives the return type.",
          },
        ],
      },
      {
        heading: "Config",
        blocks: [
          {
            type: "p",
            text: "`PORT` — listening port. Default `3000`.",
          },
        ],
      },
      {
        heading: "Dev",
        blocks: [
          {
            type: "code",
            language: "sh",
            code: "make build\nmake typecheck\nmake test",
          },
        ],
      },
      {
        heading: "Releases",
        blocks: [
          {
            type: "p",
            text: "A GitHub Actions workflow (`.github/workflows/release.yml`) runs on every push to `main`. It derives the next semantic version from commit messages since the last tag, builds a single self-contained executable via Node.js Single Executable Applications (SEA), and publishes it as a release asset.",
          },
          {
            type: "table",
            headers: ["Commit prefix", "Version bump"],
            rows: [
              ["FEAT: / feat:", "minor"],
              ["BUG: / fix:", "patch"],
              ["FEAT!: or BREAKING CHANGE in body", "major"],
              ["CHORE:, docs:, etc.", "none"],
            ],
          },
          {
            type: "p",
            text: "Build the binary locally with `make release-binary`.",
          },
        ],
      },
    ],
  },
];

function getProjectBySlug(slug) {
  return projects.find((p) => p.slug === slug) ?? null;
}

export { projects, getProjectBySlug };
